POST http://localhost:3000/register 
Content-Type: application/json

{
  "username": "adam_richardnam",
  "name": "Adam Richard",
  "password": "rich@132",
  "gender": "male",
  "location": "Detroit"
}

###


POST http://localhost:3000/login
Content-Type:application/json
{
  "username": "adam_richard",
  "password": "richrd_7"
}


###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "rich",
  "newPassword": "ric"
}

### 
